title: girls...
author: celia
email: your-email@domain.com
theme: jekyll-theme-minimal
description: > # this means to ignore newlines until "baseurl:"
  i consumed a bag of spicy potato chips and now my mouth is on fire.
  hot takes like these found only on this blog

# social links
twitter_username: almostmarlys
github_username:  celia-is-stressed

show_excerpts: true # set to false to remove excerpts on the homepage
